# basic configuration
<<<<<<< HEAD
baseurl: /course-in-a-box
=======
baseurl: /reps-edu
>>>>>>> cfb14bd890b8fc1fc204eb6324e6bec4ad140207
markdown: redcarpet
permalink: /:categories/:title/


ga_tracking_code: 
p2pu_ga_tracking_code: UA-55722824-1

# Some files we need to exclude, so Github can build the site
exclude: [Gemfile, Gemfile.lock, README.md]

defaults:
  -
    scope:
      path: "modules" # an empty string here means all files in the project
    values:
      layout: "course_page"

prose:
  media: img
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - /fonts
    - /js
    - /css

# Set some personal styles and logo for your course
# this is a hex value http://www.w3schools.com/tags/ref_colorpicker.asp
jumbotron_color: "#C13832"
jumbotron_background_image: "header.svg"
<<<<<<< HEAD
jumbotron_image: "wm-logo.png"
=======
jumbotron_image: "remo_avatar.png"
>>>>>>> cfb14bd890b8fc1fc204eb6324e6bec4ad140207
